;================================================================
; global vars
;================================================================

	extern medium start_work
	extern medium stopper
	extern medium frame_cnt
	extern medium screen_x
	extern medium screen_y
	
	extern medium player_x
	extern medium player_y
	extern medium player_dx
	extern medium player_dy
;================================================================

