extern medium player_frame ;byte, what frame the player's displaying

;-------------------------------------------------------
; player_init: initialize player sprite
;-------------------------------------------------------	
extern player_init
;-------------------------------------------------------
; player_move: handle player movement
;-------------------------------------------------------
extern player_move
